\LoadClass[a4paper,12pt]{report} 
\usepackage[utf8]{inputenc}
\usepackage{acronym} % for abbreviation
\usepackage{fancybox,fancyhdr,lscape,array,setspace} % for boxes package for header and cover
\usepackage{amsthm,amssymb,amsfonts,amsmath} % for math
\usepackage{lipsum} % for dummy text
\usepackage{multicol,multirow} % for mission ticket 
\usepackage{indentfirst} % for indentation like normal ベトナム人
\usepackage{graphicx} % for graphics
\usepackage{algorithm,algpseudocode} % for pseodocode (apt install texlive-science)

% footer
\pagestyle{fancy}
\fancyhead{}
\fancyfoot{}
\rfoot{Page \thepage}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{1pt}
