ea:    
    pop_size: 30
    num_iter: 1000
    sbxdi: 15
    pmdi: 15
    pswap: 0.5
    dimension: 50
    rmp: 0.3
    repeat: 2
    is_test: True

sgd:
    learning_rate: 0.1
    mRate: 0.01
    num_epoch: 3000
    repeat: 10
    max_eval: 150000
    train_dropout: 0.2
    test_dropout: 0.4
    useStocasticGD: 1 # 0 for vanilla BP. 1 for Stocastic BP
    useVanilla: 1 # 1 for Vanilla Gradient Descent, 0 for Gradient Descent with momentum (either regular momentum or nesterov momen)
    useNestmomen: 0 # 0 for regular momentum, 1 for Nesterov momentum

database:
    host: localhost
    user: root
    password: quang4334
    db: thesis_test
    verbose: false
    method:
        name: VARCHAR(255)

rl:
    pop_size: 20
    num_iter: 5
    sbxdi: 15
    pmdi: 15
    pswap: 0.5
    dimension: 50
    rmp: 0.3
    repeat: 30
    tasks:       
        FlappyBird: 
            name: FlappyBird
            init: 7.84
            alpha: 0.98
            unit: 'gravity'
            n_task: 3