repeat: 1
pop_size: 30
num_iter: 500
sbxdi: 2
pmdi: 5
pswap: 0.5
dimension: 50
rmp: 0.3
repeat: 1

host: localhost
user: thanh
password: BaRnEy0s@
db: mfea_ann
verbose: false

method:
    name: VARCHAR(256)

